# Generated by Django 3.2.8 on 2021-11-10 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_author"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-date"]},
        ),
    ]
